services:
  db:
    image: sysadminmichael/sentinet:db-12.3.3
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  app:
    image: sysadminmichael/sentinet:matomo-5-apache
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_PASSWORD=${DB_PASSWORD}
    ports:
      - "${MATOMO_PORT:-8081}:80"

  wp-db:
    image: sysadminmichael/sentinet:db-12.3.3
    restart: unless-stopped
    volumes:
      - wp-db:/var/lib/mysql
    environment:
      - MARIADB_PASSWORD=${WP_DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD}

  wordpress:
    image: wordpress:6-apache #plus assez de place sur le docker hub pour push une image personnalisé
    restart: unless-stopped
    depends_on:
      wp-db:
        condition: service_healthy
    volumes:
      - wp-data:/var/www/html
    environment:
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
    ports:
      - "${WP_PORT:-8082}:80"

  web:
    image: sysadminmichael/sentinet:nginx-1.27-alpine-slim
    container_name: netsentinel-site
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:80"
    read_only: true

volumes:
  db:
  matomo:
  wp-db:
  wp-data: