services:
  db:
    build: { context: ., target: db }
    image: sysadminmichael/sentinet-matomo-db:${TAG:-1.0}
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MARIADB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD manquant dans .env}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD manquant dans .env}
    networks: [back]

  app:
    build: { context: ., target: app }
    image: sysadminmichael/sentinet-matomo:${TAG:-1.0}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_PASSWORD=${DB_PASSWORD:?DB_PASSWORD manquant dans .env}
    networks: [front, back]

  wp-db:
    build: { context: ., target: wp-db }
    image: sysadminmichael/sentinet-wp-db:${TAG:-1.0}
    restart: unless-stopped
    volumes:
      - wp-db:/var/lib/mysql
    environment:
      - MARIADB_PASSWORD=${WP_DB_PASSWORD:?WP_DB_PASSWORD manquant dans .env}
      - MARIADB_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD:?WP_DB_ROOT_PASSWORD manquant dans .env}
    networks: [back]

  wordpress:
    build: { context: ., target: wordpress }
    image: sysadminmichael/sentinet-wordpress:${TAG:-1.0}
    restart: unless-stopped
    depends_on:
      wp-db:
        condition: service_healthy
    volumes:
      - wp-data:/var/www/html
    environment:
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD:?WP_DB_PASSWORD manquant dans .env}
    networks: [front, back]

  web:
    build: { context: ., target: web }
    image: sysadminmichael/sentinet-web:${TAG:-1.0}
    container_name: netsentinel-site
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks: [front]

  nginx-proxy:
    build: { context: ., target: proxy }
    image: sysadminmichael/sentinet-proxy:${TAG:-1.0}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on: [web, app, wordpress]
    networks: [front]

networks:
  front:
  back:
    internal: true

volumes:
  db:
  matomo:
  wp-db:
  wp-data: